-- Retired: this script associated generic stock photos with unrelated exercises.
-- Do not restore the old Unsplash UPDATE statements.
-- Exercise images must be reviewed against the movement and equipment before use.
-- Corrections preserve previous image URLs in exercises.version_history.
-- No data changes are performed by this file.
