-- SCRIPT DE PREENCHIMENTO DE INSTRUÇÕES TÉCNICAS (RUBI AI)
-- Este script preenche as instruções de execução para os exercícios base da biblioteca.

UPDATE public.exercises SET instructions = '1. Posicione a barra na parte superior das costas (trapézio).\n2. Mantenha os pés afastados na largura dos ombros.\n3. Agache controladamente enviando o quadril para trás até as coxas ficarem paralelas ao chão.\n4. Empurre o chão com força para retornar à posição inicial.\n\n⚠️ DICAS TÉCNICAS: Mantenha o peito aberto e o core contraído durante todo o movimento.' WHERE name = 'Agachamento Livre' AND (instructions IS NULL OR instructions = '');

UPDATE public.exercises SET instructions = '1. Sente-se no aparelho com as costas bem apoiadas.\n2. Posicione os pés na plataforma na largura dos ombros.\n3. Desça a plataforma controladamente até os joelhos formarem um ângulo de 90 graus.\n4. Empurre a plataforma sem bloquear totalmente os joelhos no topo.\n\n⚠️ DICAS TÉCNICAS: Evite tirar o quadril do banco durante a fase de descida.' WHERE name = 'Leg Press 45' AND (instructions IS NULL OR instructions = '');

UPDATE public.exercises SET instructions = '1. Sente-se e ajuste o apoio de pernas.\n2. Segure a barra com pegada aberta e palmas para frente.\n3. Puxe a barra em direção à parte superior do peito, inclinando levemente o tronco para trás.\n4. Retorne controladamente alongando bem as dorsais.\n\n⚠️ DICAS TÉCNICAS: Use os cotovelos para puxar o peso, focando na contração das costas e não apenas nos braços.' WHERE name = 'Puxada Frente' AND (instructions IS NULL OR instructions = '');

UPDATE public.exercises SET instructions = '1. Ajuste o banco em uma inclinação de 30 a 45 graus.\n2. Inicie com os halteres acima do peito, braços estendidos.\n3. Desça os halteres lateralmente até a linha do peito.\n4. Empurre de volta ao centro de forma explosiva mas controlada.\n\n⚠️ DICAS TÉCNICAS: Foco na parte superior do peitoral. Mantenha as escápulas retraídas.' WHERE name = 'Supino Inclinado com Halteres' AND (instructions IS NULL OR instructions = '');

UPDATE public.exercises SET instructions = '1. Fique em pé, coluna neutra, segurando a barra EZ.\n2. Mantenha os cotovelos colados ao corpo.\n3. Flexione os braços trazendo a barra em direção aos ombros.\n4. Desça lentamente até a extensão quase completa.\n\n⚠️ DICAS TÉCNICAS: Evite balançar o corpo para subir o peso. Controle a descida (fase excêntrica).' WHERE name = 'Rosca Direta (Barra EZ)' AND (instructions IS NULL OR instructions = '');

UPDATE public.exercises SET instructions = '1. Posicione-se de frente para a polia alta.\n2. Segure a barra com as palmas voltadas para baixo.\n3. Empurre a barra para baixo até estender completamente os braços.\n4. Retorne até os antebraços ficarem paralelos ao chão.\n\n⚠️ DICAS TÉCNICAS: Mantenha os cotovelos imóveis ao lado das costelas durante todo o exercício.' WHERE name = 'Tríceps Pulley' AND (instructions IS NULL OR instructions = '');

UPDATE public.exercises SET instructions = '1. Sente-se com as costas apoiadas e braços estendidos acima da cabeça.\n2. Desça os halteres lateralmente até ficarem alinhados com as orelhas.\n3. Empurre os halteres para cima aproximando-os levemente no topo.\n4. Mantenha o controle total da carga na descida.\n\n⚠️ DICAS TÉCNICAS: Evite bater os halteres no topo e mantenha o abdômen firme.' WHERE name = 'Desenvolvimento Halteres' AND (instructions IS NULL OR instructions = '');
